[server]
enable = true

[libraries]
# Assign separate libraries for each project
lab0_lib.files = [
    "LAB0/src/**/*.vhd",
    "LAB0/sim/**/*.vhd"
]

lab1_lib.files = [
    "LAB1/src/**/*.vhd",
    "LAB1/sim/**/*.vhd"
]

# lab2_lib.files = [
#     "LAB2/src/**/*.vhd",
#     "LAB2/sim/**/*.vhd"
# ]

# lab3_lib.files = [
#     "LAB3/src/**/*.vhd",
#     "LAB3/sim/**/*.vhd"
# ]

[analyses]
on_save = true
on_open = true

[ghdl]
standard = "08"
library_path = [
    "C:/Xilinx/Vivado/2020.2/data/vhdl/src"
]

[vhdl]
standard = "2008"
