[libraries]
# Assign separate libraries for each project
lab0_lib.files = [
    "LAB0/src/**/*.vhd",
    "LAB0/sim/**/*.vhd"
]

lab1_lib.files = [
    "LAB1/src/**/*.vhd",
    "LAB1/sim/**/*.vhd"
]

lab2_lib.files = [
    "LAB2/src/*.vhd",
    "LAB2/sim/**/*.vhd"
]

# lab3_lib.files = [
#     "LAB3/src/**/*.vhd",
#     "LAB3/sim/**/*.vhd"
# ]

xpm.files = [
  "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd"
]
xpm.is_third_party = true

unisim.files = [
  "C:/Xilinx/Vivado/2020.2/data/vhdl/src/unisims/**/*.vhd"
]
unisim.is_third_party = true